// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHDsURhfaHo4J0rIOZyJX3_JMSnTkXrE',
    appId: '1:964103493674:web:7c404184fc646b09fe8b53',
    messagingSenderId: '964103493674',
    projectId: 'fir-flutter-codelab-db5d3',
    authDomain: 'fir-flutter-codelab-db5d3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-db5d3.appspot.com',
    measurementId: 'G-W2KY5J7DHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnasqRsvSKBe8toNyIHy1aGcnarY4OUGw',
    appId: '1:964103493674:android:af976c8dd90c7e1dfe8b53',
    messagingSenderId: '964103493674',
    projectId: 'fir-flutter-codelab-db5d3',
    storageBucket: 'fir-flutter-codelab-db5d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmJcbTYFeL1ggjUfoQSCIyifrawbMv8fQ',
    appId: '1:964103493674:ios:243f725645c23faafe8b53',
    messagingSenderId: '964103493674',
    projectId: 'fir-flutter-codelab-db5d3',
    storageBucket: 'fir-flutter-codelab-db5d3.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmJcbTYFeL1ggjUfoQSCIyifrawbMv8fQ',
    appId: '1:964103493674:ios:243f725645c23faafe8b53',
    messagingSenderId: '964103493674',
    projectId: 'fir-flutter-codelab-db5d3',
    storageBucket: 'fir-flutter-codelab-db5d3.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADHDsURhfaHo4J0rIOZyJX3_JMSnTkXrE',
    appId: '1:964103493674:web:815167153cc139d1fe8b53',
    messagingSenderId: '964103493674',
    projectId: 'fir-flutter-codelab-db5d3',
    authDomain: 'fir-flutter-codelab-db5d3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-db5d3.appspot.com',
    measurementId: 'G-1HVVRMZXTY',
  );

}